### ISSUE TITLE
Create github page for project

### ISSUE THREAD

**Issue by GeekAb** [GeekAb/js-ordinal#5]
Thinking to create github page for this project. To start with idea is to add following details

- Documentation
- Link to npmjs.com package page.
- Todo list

**Comment by ThiagoAugustoSM** [comment]
I'm on it @GeekAb !

**Comment by GeekAb** [comment]
Thanks @ThiagoAugustoSM

**Comment by GeekAb** [comment]
Thanks @ThiagoAugustoSM 

Fixed with #7
